### ISSUE TITLE
Modify operator to use operator-sdk v0.19.2 

### ISSUE THREAD

**Issue by HariNarayananMohan** [openshift/etcd-ha-operator#11]
The operator currently uses operator-sdk v0.9.0 which is old. The operator needs to upgraded to recent versions.

**Comment by HariNarayananMohan** [comment]
@hexfusion  @alaypatel07 This includes rebuilding the operator image. Can you give access to push the image to this repo https://quay.io/repository/alaypatel07/etcd-ha-operator or creating a new repo works as well.

**Comment by hexfusion** [comment]
@HariNarayananMohan you can raise a PR and we will gladly merge it.
